# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

gems: [jekyll-paginate]

# Setup
title:               scott's beer recipes
tagline:             'yum'
description:         'my beer recipes'
baseurl:             /beer_recipes/
paginate:            3
exclude: 						['_posts/todo/']

# About/contact
github: 						 https://github.com/sckott/beer_recipes
author:
  name:              Scott Chamberlain
  url:               https://twitter.com/recology_
  email:             myrmecocystus@gmail.com
